# Generated by Django 4.2.24 on 2025-09-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('picture', models.ImageField(upload_to='product_images/')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'liste des produits',
                'db_table': 'products',
                'managed': True,
            },
        ),
    ]
